export const serverURL: string = 'https://qwertynext.com/api/v1'
export const set_currency: string = 'руб.'
export const set_phone: string = '+7 (123) 456 78 90'
export const set_phoneNum: string = '+71234567890'
export const errorText: string = 'Обязательное поле'