import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.scss'
import Header from './components/Header/Header'
import Providers from './store/Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Header />
          <div className="container main_container">
            {children}
          </div>
        </body>
      </Providers>
    </html>
  )
}
